<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #333; margin: 0; }
    .header { display: table; width: 100%; margin-bottom: 30px; }
    .header-left { display: table-cell; vertical-align: top; width: 60%; }
    .header-right { display: table-cell; vertical-align: top; text-align: right; }
    .company-name { font-size: 20px; font-weight: bold; color: #1a1a2e; }
    .doc-title { font-size: 22px; font-weight: bold; color: #0891b2; margin: 0; }
    .doc-number { font-size: 12px; color: #666; }
    .divider { border: none; border-top: 2px solid #0891b2; margin: 15px 0; }
    .deliver-to h4 { font-size: 10px; text-transform: uppercase; color: #999; margin: 0 0 5px 0; letter-spacing: 1px; }
    .deliver-to p { margin: 2px 0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    thead th { background: #0891b2; color: white; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; }
    thead th.right { text-align: right; }
    tbody td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    tbody td.right { text-align: right; }
    tfoot td { padding: 8px 10px; font-weight: bold; border-top: 2px solid #0891b2; }
    tfoot td.right { text-align: right; }
    .signature-block { margin-top: 50px; display: table; width: 100%; }
    .sig-cell { display: table-cell; width: 45%; text-align: center; }
    .sig-line { border-top: 1px solid #333; margin-top: 40px; padding-top: 5px; font-size: 10px; color: #666; }
    .footer { margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; font-size: 10px; color: #999; text-align: center; }
</style>
</head>
<body>

<?php
$dnNumber = 'DN-' . date('Y') . '-' . str_pad($project['id'], 4, '0', STR_PAD_LEFT);
$deliveryTotal = array_sum(array_column($project['delivery_items'], 'total_price'));
?>

<div class="header">
    <div class="header-left">
        <div class="company-name">MunyiraHQ</div>
        <div style="color:#666; margin-top:4px;">Financial Management System</div>
    </div>
    <div class="header-right">
        <div class="doc-title">DELIVERY NOTE</div>
        <div class="doc-number"><?= $dnNumber ?></div>
        <div style="margin-top:6px; color:#666;">
            Date: <?= date('d F Y') ?>
        </div>
    </div>
</div>

<hr class="divider">

<div class="deliver-to" style="margin-bottom:20px;">
    <h4>Deliver To</h4>
    <p><strong><?= esc($project['party_name']) ?></strong></p>
    <?php if (!empty($project['phone'])): ?>
        <p><?= esc($project['phone']) ?></p>
    <?php endif; ?>
    <?php if (!empty($project['address'])): ?>
        <p><?= esc($project['address']) ?></p>
    <?php endif; ?>
</div>

<p><strong>Project:</strong> <?= esc($project['title']) ?></p>
<?php if (!empty($project['description'])): ?>
    <p style="color:#666;"><?= esc($project['description']) ?></p>
<?php endif; ?>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Item / Description</th>
            <th class="right">Quantity</th>
            <th class="right">Unit Price (KES)</th>
            <th class="right">Total (KES)</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($project['delivery_items'] as $i => $item): ?>
        <tr>
            <td style="color:#999;"><?= $i + 1 ?></td>
            <td><?= esc($item['name']) ?></td>
            <td class="right"><?= $item['quantity'] ?></td>
            <td class="right"><?= number_format((float)$item['unit_price'], 2) ?></td>
            <td class="right"><?= number_format((float)$item['total_price'], 2) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">Total Items: <?= count($project['delivery_items']) ?></td>
            <td class="right">KES <?= number_format($deliveryTotal, 2) ?></td>
        </tr>
    </tfoot>
</table>

<p style="background:#f0f9ff; padding:10px; border-radius:4px; border-left:3px solid #0891b2;">
    <strong>Please inspect all items upon receipt and report any discrepancies within 24 hours.</strong>
</p>

<div class="signature-block">
    <div class="sig-cell">
        <div class="sig-line">Delivered by (Name & Signature)</div>
    </div>
    <div class="sig-cell" style="float:right;">
        <div class="sig-line">Received by (Name, Signature & Date)</div>
    </div>
</div>

<div class="footer">
    Generated by MunyiraHQ · <?= date('d F Y H:i') ?> · <?= $dnNumber ?>
</div>

</body>
</html>
